language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - python src/manage.py test
  - coverage run --omit */virtualenvs/* src/manage.py test
  - coverage report -m

deploy:
  provider: script
  skip_cleanup: true
  script: echo "deploying..."
  on:
    branch: master
