language: python
python:
  - 3.6
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install: 
  - pip install pipenv
  - pipenv install

script:
  - pipenv run python src/manage.py test
  - pipenv run coverage --omit */virtualenvs/* run src/manage.py test
  - pipenv run coverage report -m

deploy:
  provider: script
  skip_cleanup: true
  script: echo "deploying..."
  on:
    branch: master
