version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pushd src
            pip install -r requirements.txt
            popd

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "src/requirements.txt" }}
        
      - run:
          name: Run Tests
          command: |
            pushd tests
            python3 test.py
            popd
